//to run server: npx http-server
import DbActions from "./DbActionsAPIs";


/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Any other custom service worker logic can go here.

//#########################################################################33
const CACHE_NAME = 'app1-v1.0.0.0';

// The list of files to cache
const filesToCache = [
    // The root of the app
    '/',
    // The HTML file
    '/index.html',
    // The manifest file
    '/manifest.json'
  ];

// Use the install event to pre-cache all initial resources.
self.addEventListener('install', event => {
    console.log('Installing..')
    
    self.skipWaiting();
    event.waitUntil((async () => {
        const cache = await caches.open(CACHE_NAME);
        cache.addAll([
        '/'//,
        // '/index.html',
        // '/src/main.jsx',
        // '/manifest.json',
        // '/logo192.png',
        // '/vite.svg',
        // '/@vite/client',
        // '/@react-refresh',
        
        


        // , 'style.css'
        //,'/converter.js' ,'/converter.css'
        ]);
        // cache.addAll(filesToCache)
    })());
    console.log('Completed Installing.')
});

self.addEventListener("activate", function(event) {
  // Claim control of the current page
    //event.waitUntil(clients.claim());
});

self.addEventListener('fetch', event => {
    // const method = event.metho
    // console.log(actionTime, method, 'Fetching..1.1.1 ')
    event.respondWith(GetResponse(event));
});

async function GetResponse(event){
    const method = event.request.clone().method
    const actionTime = Date.now()
    try {    
        //console.log(actionTime, event.request.clone())
        // console.log(actionTime, method, 'Fetching..1.1.1 ')
        
        const fetchResponse = await fetch(event.request.clone());
        // Save the resource in the cache and return it.
        const cache = await caches.open(CACHE_NAME);
        if(method == 'GET'){
            // console.log(actionTime, 'Fetching..1.1.2 ')
            try{
                cache.put(event.request.clone(), fetchResponse.clone()).then(()=>{
                    // console.log(actionTime, 'Fetching..31 ')
                })
                .catch(err=>{console.log(actionTime, "then error..", err)})
            }catch (ex1){
                console.log("Putting error..", ex1)
            }   
        }
        return fetchResponse;
    } catch (e) {
        // The network failed.
        console.log(actionTime, 'No netwoerk found, trying to get from cache...')
        console.log(e, event.request.clone())
        
        // Try to get the resource from the cache.
        const cache = await caches.open(CACHE_NAME);
        const cachedResponse = await cache.match(event.request);
        if (cachedResponse) {
            return cachedResponse;
        } else {
            //console.log('Fetching..5')
            console.log('No caches found.')
        }
    }    
}

// self.addEventListener('fetch', event => {
//     event.respondWith(GetResponse(event));
// });

// // add a sync event listener
// self.addEventListener("sync", event => {
//     console.log("Syncing..");
//     // check the tag of the sync event
//     if (event.tag === "delete-waiting") {
//       // perform some actions when the sync event is fired
//       console.log("Sync event fired..");
//       // read products table from indexedDB and save them to MongoDB
//       // you can use Dexie and Dexie.Syncable to simplify the process
//       // see the following websites for more details
//       // [Dexie.js - Minimalistic IndexedDB Wrapper](https://stackoverflow.com/questions/53381870/service-workers-and-indexeddb)
//       // [Dexie.Syncable](https://stackoverflow.com/questions/76633228/how-can-i-sync-my-indexeddb-data-to-my-mongodb)
//     }
// });

self.addEventListener("sync", event => {
    // fetch("http://127.0.0.1:4002/api/subsc").then(res=>{
    //     if(res.ok){
    //         console.log(res)
    //         return res.json()
    //     }
    //     // console.log(res.body)
    // }).then(data => console.log(data))
    // if(event.)
    console.log("syncing..")
    // DbActions.Sync()
    DbActions.Sync()
    .then(() => console.log('Sync operation successful!'))
    .catch(() => {
      // Sync failed, so reregister for another attempt
      return self.registration.sync.register('waiting');
    })
})




